2024-01-23 19:50:19,984 - pyswarms.single.global_best - INFO - Optimize for 100 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2024-01-23 19:51:28,848 - pyswarms.single.global_best - INFO - Optimize for 100 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2024-01-23 19:52:10,724 - pyswarms.single.global_best - INFO - Optimize for 100 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2024-01-23 19:53:36,735 - pyswarms.single.global_best - INFO - Optimize for 100 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2024-01-23 19:54:07,440 - pyswarms.single.global_best - INFO - Optimize for 100 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2024-01-23 19:54:40,623 - pyswarms.single.global_best - INFO - Optimize for 100 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2024-01-23 19:55:21,516 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyswarms/backend/generators.py", line 74, in generate_swarm
    lb, ub = bounds
    ^^^^^^
ValueError: too many values to unpack (expected 2)
2024-01-23 19:55:23,902 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyswarms/backend/generators.py", line 74, in generate_swarm
    lb, ub = bounds
    ^^^^^^
ValueError: too many values to unpack (expected 2)
2024-01-23 19:56:06,529 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyswarms/backend/generators.py", line 74, in generate_swarm
    lb, ub = bounds
    ^^^^^^
ValueError: too many values to unpack (expected 2)
2024-01-23 20:09:47,392 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyswarms/backend/generators.py", line 74, in generate_swarm
    lb, ub = bounds
    ^^^^^^
ValueError: too many values to unpack (expected 2)
2024-01-23 20:10:28,586 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyswarms/backend/generators.py", line 74, in generate_swarm
    lb, ub = bounds
    ^^^^^^
ValueError: too many values to unpack (expected 2)
2024-01-23 20:11:21,304 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyswarms/backend/generators.py", line 74, in generate_swarm
    lb, ub = bounds
    ^^^^^^
ValueError: too many values to unpack (expected 2)
2024-01-23 20:11:31,669 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyswarms/backend/generators.py", line 74, in generate_swarm
    lb, ub = bounds
    ^^^^^^
ValueError: too many values to unpack (expected 2)
2024-01-23 20:12:10,239 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyswarms/backend/generators.py", line 74, in generate_swarm
    lb, ub = bounds
    ^^^^^^
ValueError: too many values to unpack (expected 2)
2024-01-23 20:12:17,068 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyswarms/backend/generators.py", line 74, in generate_swarm
    lb, ub = bounds
    ^^^^^^
ValueError: too many values to unpack (expected 2)
2024-01-23 20:12:20,156 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyswarms/backend/generators.py", line 74, in generate_swarm
    lb, ub = bounds
    ^^^^^^
ValueError: too many values to unpack (expected 2)
2024-01-23 20:16:02,694 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyswarms/backend/generators.py", line 74, in generate_swarm
    lb, ub = bounds
    ^^^^^^
ValueError: too many values to unpack (expected 2)
2024-01-23 20:25:38,499 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyswarms/backend/generators.py", line 74, in generate_swarm
    lb, ub = bounds
    ^^^^^^
ValueError: too many values to unpack (expected 2)
2024-01-23 20:26:09,832 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyswarms/backend/generators.py", line 74, in generate_swarm
    lb, ub = bounds
    ^^^^^^
ValueError: too many values to unpack (expected 2)
2024-01-23 20:26:51,946 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyswarms/backend/generators.py", line 74, in generate_swarm
    lb, ub = bounds
    ^^^^^^
ValueError: too many values to unpack (expected 2)
2024-01-23 20:28:18,805 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyswarms/backend/generators.py", line 74, in generate_swarm
    lb, ub = bounds
    ^^^^^^
ValueError: too many values to unpack (expected 2)
2024-01-23 20:29:37,110 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyswarms/backend/generators.py", line 74, in generate_swarm
    lb, ub = bounds
    ^^^^^^
ValueError: too many values to unpack (expected 2)
2024-01-23 20:31:40,767 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyswarms/backend/generators.py", line 74, in generate_swarm
    lb, ub = bounds
    ^^^^^^
ValueError: too many values to unpack (expected 2)
2024-01-23 20:31:45,462 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyswarms/backend/generators.py", line 74, in generate_swarm
    lb, ub = bounds
    ^^^^^^
ValueError: too many values to unpack (expected 2)
2024-01-23 20:35:38,475 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (6,)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyswarms/backend/generators.py", line 74, in generate_swarm
    lb, ub = bounds
    ^^^^^^
ValueError: too many values to unpack (expected 2)
